# Generated by Django 3.1.1 on 2020-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profiles/default.jpg', max_length=250, upload_to='profiles'),
        ),
    ]
