# Generated by Django 3.0.7 on 2020-07-02 05:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=20)),
                ('short_desc', ckeditor.fields.RichTextField()),
                ('desc', ckeditor.fields.RichTextField()),
                ('url', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Catagory')),
            ],
        ),
        migrations.AddField(
            model_name='catagory',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Root'),
        ),
    ]
