# Generated by Django 3.0.7 on 2020-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
