# Generated by Django 3.1.1 on 2020-10-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
