# Generated by Django 3.0.7 on 2020-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200706_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
