# Generated by Django 3.1.1 on 2020-10-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201022_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='price',
        ),
    ]
